export const presentationData = {
    meta: {
        title: "もしも建設業跡取りが再びSEに転生したら",
        presenter: "松井 大樹",
        company: "株式会社Sei San Sei"
    },
    slides: [
        // 0. Title
        {
            type: "title",
            title: "もしも建設業跡取りが<br>再びSEに転生したら",
            subtitle: "SIerから建設現場、そしてLarkエバンジェリストへ",
            footer: "株式会社Sei San Sei | 松井 大樹"
        },
        // 1. Intro: Who am I
        {
            type: "bento",
            title: "Who am I?",
            items: [
                { label: "Past", text: "東京のSIer (6年)", icon: "💻" },
                { label: "U-Turn", text: "浜松の建設会社 跡取り", icon: "🏗️" },
                { label: "Now", text: "Larkエバンジェリスト", icon: "🐦", highlight: true }
            ]
        },
        // 2. The Hook
        {
            type: "big-statement",
            text: "なぜ「転生」なのか？",
            subtext: "デジタルとアナログを行き来した、数奇な物語。"
        },
        // 3. Reality
        {
            type: "list",
            title: "建設業経営の現実",
            items: [
                "紙だらけの業務",
                "鳴り止まない電話",
                "散在する情報"
            ],
            highlight: "「跡取りとして結果が出せない...」"
        },
        // 4. Meeting Lark
        {
            type: "hero",
            title: "Lark",
            subtitle: "The Superapp for Work",
            description: "Chat + Docs + Video + Approval",
            gradient: true
        },
        // 5. Why it Clicked
        {
            type: "quote",
            text: "それは単なるツールではない。<br>会社の「神経系」だ。",
            author: "SE × 建設業の視点"
        },
        // 6. BPaaS
        {
            type: "equation",
            left: "Lark",
            operator: "+",
            right: "RPA",
            result: "BPaaS",
            description: "Business Process as a Service"
        },
        // 7. Why BPaaS
        {
            type: "big-statement",
            text: "人手不足は<br>「仕組み」で救う。",
            subtext: "中小企業こそ、自動化の恩恵を。"
        },
        // 8. Turning Point
        {
            type: "dark",
            title: "人生は一度",
            subtitle: "母が残したメッセージ",
            text: "自分の熱量を、本当に注ぎたいものは何か？"
        },
        // 9. The Decision
        {
            type: "image-text",
            title: "2025.09 決断",
            text: "家業を離れ、Larkの道へ。<br>株式会社Sei San Seiへの参画。",
            highlight: "建設業 × Lark に全てを懸ける"
        },
        // 10. Mission
        {
            type: "grid",
            title: "Current Mission",
            items: ["不動産", "建設", "鋼材", "福祉", "化粧品"],
            footer: "業種は違っても、課題は同じ。"
        },
        // 11. Message
        {
            type: "big-statement",
            text: "デジタルは怖くない。",
            subtext: "「変わりたい」という想いがあればいい。"
        },
        // 12. AI Reveal
        {
            type: "reveal",
            title: "One More Thing...",
            text: "このプレゼン資料、構成、デザイン、<br>そしてコードの全て。",
            revealText: "Generated by AI",
            subtext: "Google Gemini & Antigravity"
        },
        // 13. Closing
        {
            type: "title",
            title: "Thank You",
            subtitle: "建設業の新しい形を、共に創りましょう。",
            footer: "株式会社Sei San Sei | 松井 大樹"
        }
    ]
};
